# Generated by Django 5.0.6 on 2024-08-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='content',
        ),
    ]
